/**
 * generated by Xtext 2.13.0
 */
package wodel.dsls.ui.contentassist;

import wodel.dsls.ui.contentassist.AbstractWodelProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class WodelProposalProvider extends AbstractWodelProposalProvider {
}
