/**
 * generated by Xtext 2.13.0
 */
package wodeledu.dsls.validation;

import wodeledu.dsls.validation.AbstractModelDrawValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ModelDrawValidator extends AbstractModelDrawValidator {
}
