/*
 * generated by Xtext 2.13.0
 */
package wodeledu.dsls.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractModelDrawScopeProvider extends DelegatingScopeProvider {
}
