/*
 * generated by Xtext
 */
package wodel.dsls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AspleUiModule extends wodel.dsls.ui.AbstractAspleUiModule {
	public AspleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
