/*
 * generated by Xtext
 */
package org.mutatortests.validation

import org.eclipse.xtext.validation.Check
import mutatortests.MutatorTests
import java.io.File
import manager.ModelManager
import mutatortests.Test

//import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TestsValidator extends AbstractTestsValidator {

    public static val INVALID_MODEL = 'invalidModel'
    public static val FILE_NOT_FOUND = 'fileNotFound'
	
	@Check
    def checkSources(MutatorTests mts) {
//    	if (mts.tests != null) {
//    		for (Test test : mts.tests) {
//    			var File file = new File(ModelManager.getMetaModelPath() + "\\" + test.source)
//				if (file.isFile() == true) {
//					if (file.getPath().endsWith(".model") == true) {
//						if (! ModelManager.checkModel(file.getPath()))
//    	   					error("Cannot find model " + file.getPath(), null, INVALID_MODEL);
//					}
//				}
//				else {
//					error("Cannot find file " + test.source, null, FILE_NOT_FOUND);
//				}
//			}
//   	    }
    	/*if (this.packages != null && this.packages.size()>0)
	    	try {
				this.model = ModelManager.loadModel(this.packages, p.model)			
			} catch ( ModelNotFoundException e ) {
				error(e.toString(), null, INVALID_MODEL)
			}*/
    }
//  public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MyDslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
}
