/*
 * generated by Xtext 2.37.0
 */
package wodel.dsls.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import com.google.inject.Inject
import org.eclipse.core.runtime.Platform
import wodel.dsls.imports.WodelImporterResolver
import mutatorenvironment.MutatorEnvironment
import mutatorenvironment.Library

/**
 * @author Pablo Gomez-Abajo - Main Wodel code generator.
 * 
 * It calls WodelMutatorGenerator to generate the Java code for the mutations,
 * and WodelUseGenerator to generate the USE code for the seeds synthesizer. 
 */
class WodelGenerator extends AbstractGenerator {

	@Inject WodelDynamicMutatorGenerator mutatorDynamicGenerator
	@Inject WodelStandaloneMutatorGenerator mutatorStandaloneGenerator
	@Inject WodelUseGenerator useGenerator
	@Inject WodelDynamicAPIGenerator dynamicApiGenerator
	@Inject WodelStandaloneAPIGenerator standaloneApiGenerator
	
	@Inject WodelImporterResolver importerResolver
	
	override doGenerate(Resource input, IFileSystemAccess2 fsa, IGeneratorContext context) {
		val environment = input.contents.get(0) as MutatorEnvironment
		/*
		 * A library is reusable source material.
		 * It does not generate executable artifacts itself.
		 */
		if (environment.definition instanceof Library) {
			return
		}
		
		/*
		 * From this point onward every generator receives the
		 * flattened/effective program.
		 */
		val resolvedInput = importerResolver.resolve(input)
		
		mutatorDynamicGenerator.doGenerate(resolvedInput, fsa, context)
		mutatorStandaloneGenerator.doGenerate(resolvedInput, fsa, context)
		try {
			var boolean seedModelSynthesis = Platform.getPreferencesService().getBoolean("wodel.dsls.Wodel", "Seed model synthesis", false, null);
			if (seedModelSynthesis == true) {
				useGenerator.doGenerate(resolvedInput, fsa, context)
			}
		} catch (Exception ex) {}
		dynamicApiGenerator.doGenerate(resolvedInput, fsa, context)
		standaloneApiGenerator.doGenerate(resolvedInput, fsa, context)
	}
}
