/*
 * generated by Xtext
 */
package wodel.dsls;

import org.eclipse.xtext.scoping.IScopeProvider;

import com.google.inject.Binder;

import wodel.dsls.scoping.WodelScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class WodelRuntimeModule extends wodel.dsls.AbstractWodelRuntimeModule {

}
