/**
 * generated by Xtext 2.13.0
 */
package wodeledu.dsls.ide;

import wodeledu.dsls.ide.AbstractEduTestIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EduTestIdeModule extends AbstractEduTestIdeModule {
}
