/**
 * generated by Xtext
 */
package wodeledu.dsls.serializer;

import wodeledu.dsls.serializer.AbstractEduTestSyntacticSequencer;

@SuppressWarnings("all")
public class EduTestSyntacticSequencer extends AbstractEduTestSyntacticSequencer {
}
