/**
 *
 * $Id$
 */
package mutatorenvironment.validation;

import mutatorenvironment.miniOCL.InvariantCS;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

/**
 * A sample validator interface for {@link mutatorenvironment.Constraint}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstraintValidator {
	boolean validate();

	boolean validateId(String value);
	boolean validateType(EClass value);
	boolean validateExpressions(EList<InvariantCS> value);
	boolean validateRules(EList<String> value);
}
