/**
 *
 * $Id$
 */
package mutatorenvironment.validation;

import mutatorenvironment.AttributeSet;
import mutatorenvironment.ObSelectionStrategy;
import mutatorenvironment.ReferenceSet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mutatorenvironment.CreateObjectMutator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CreateObjectMutatorValidator {
	boolean validate();

	boolean validateContainer(ObSelectionStrategy value);
	boolean validateAttributes(EList<AttributeSet> value);
	boolean validateReferences(EList<ReferenceSet> value);
}
