/**
 *
 * $Id$
 */
package mutatorenvironment.validation;

import mutatorenvironment.AttributeType;

import org.eclipse.emf.ecore.EAttribute;

/**
 * A sample validator interface for {@link mutatorenvironment.ReferenceAtt}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReferenceAttValidator {
	boolean validate();

	boolean validateAttribute(EAttribute value);
	boolean validateValue(AttributeType value);
}
