/**
 *
 * $Id$
 */
package mutatorenvironment.validation;

import mutatorenvironment.AttributeEvaluationType;
import mutatorenvironment.ObSelectionStrategy;

import mutatorenvironment.Operator;
import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EReference;

/**
 * A sample validator interface for {@link mutatorenvironment.ReferenceEvaluation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ReferenceEvaluationValidator {
	boolean validate();

	boolean validateName(EReference value);
	boolean validateRefName(EReference value);
	boolean validateRefRefName(EReference value);
	boolean validateOperator(Operator value);

	boolean validateValue(ObSelectionStrategy value);
	boolean validateRefType(EReference value);
	boolean validateAttName(EAttribute value);
	boolean validateAttValue(AttributeEvaluationType value);

	boolean validateContainer(boolean value);
}
