/**
 *
 * $Id$
 */
package mutatorenvironment.validation;

import mutatorenvironment.ObSelectionStrategy;
import mutatorenvironment.SampleClause;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EStructuralFeature;

/**
 * A sample validator interface for {@link mutatorenvironment.SelectSampleMutator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SelectSampleMutatorValidator {
	boolean validate();

	boolean validateObject(ObSelectionStrategy value);
	boolean validateClause(SampleClause value);
	boolean validateFeatures(EList<EStructuralFeature> value);
}
