/**
 * generated by Xtext
 */
package org.identifyelements.serializer;

import org.identifyelements.serializer.AbstractIdentifyElementsSemanticSequencer;

@SuppressWarnings("all")
public class IdentifyElementsSemanticSequencer extends AbstractIdentifyElementsSemanticSequencer {
}
