package wodeledu.dsls.generator;

import com.google.common.collect.Iterables;
import java.util.ArrayList;
import java.util.List;
import modeldraw.MutatorDraw;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import wodel.utils.manager.JavaUtils;
import wodel.utils.manager.ModelManager;

/**
 * @author Pablo Gomez-Abajo - modelDraw Python code generator.
 * 
 * Generates Java code that renders model instances as Python source and
 * syntax-highlighted HTML. Runtime paths are resolved by the generated class;
 * no workspace-specific locations are embedded at generation time.
 */
@SuppressWarnings("all")
public class ModelDrawPyCodeGenerator extends AbstractGenerator {
  private String fileName;

  private String className;

  private List<EPackage> metamodel;

  private List<EClass> roots;

  private String rootName;

  private String metamodelFileName;

  private String lastSegment(final String value) {
    String _xblockexpression = null;
    {
      if (((value == null) || value.isEmpty())) {
        return "";
      }
      final String normalized = value.replace("\\", "/");
      final int slash = normalized.lastIndexOf("/");
      String _xifexpression = null;
      if ((slash >= 0)) {
        _xifexpression = normalized.substring((slash + 1));
      } else {
        _xifexpression = normalized;
      }
      _xblockexpression = _xifexpression;
    }
    return _xblockexpression;
  }

  private String baseName(final String value) {
    String _xblockexpression = null;
    {
      if (((value == null) || value.isEmpty())) {
        return "Model";
      }
      String name = value;
      boolean _endsWith = name.endsWith(".draw");
      if (_endsWith) {
        int _length = name.length();
        int _length_1 = ".draw".length();
        int _minus = (_length - _length_1);
        name = name.substring(0, _minus);
      }
      _xblockexpression = name.replace(".", "_");
    }
    return _xblockexpression;
  }

  private String javaString(final String value) {
    String _xblockexpression = null;
    {
      if ((value == null)) {
        return "";
      }
      _xblockexpression = value.replace("\\", "\\\\").replace("\"", "\\\"");
    }
    return _xblockexpression;
  }

  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    try {
      URI _uRI = null;
      if (resource!=null) {
        _uRI=resource.getURI();
      }
      String _lastSegment = null;
      if (_uRI!=null) {
        _lastSegment=_uRI.lastSegment();
      }
      final String sourceBaseName = this.baseName(_lastSegment);
      int index = 0;
      Iterable<MutatorDraw> _filter = Iterables.<MutatorDraw>filter(IteratorExtensions.<EObject>toIterable(resource.getAllContents()), MutatorDraw.class);
      for (final MutatorDraw draw : _filter) {
        {
          String _xifexpression = null;
          if ((index == 0)) {
            _xifexpression = sourceBaseName;
          } else {
            _xifexpression = (sourceBaseName + Integer.valueOf(index));
          }
          final String generatedBaseName = _xifexpression;
          this.className = generatedBaseName;
          this.fileName = (generatedBaseName + "Draw.java");
          ArrayList<EPackage> _arrayList = new ArrayList<EPackage>();
          this.metamodel = _arrayList;
          this.metamodel.addAll(ModelManager.loadMetaModel(draw.getMetamodel()));
          ArrayList<EClass> _arrayList_1 = new ArrayList<EClass>();
          this.roots = _arrayList_1;
          this.roots.addAll(ModelManager.getRootEClasses(this.metamodel));
          String _xifexpression_1 = null;
          boolean _isEmpty = this.roots.isEmpty();
          if (_isEmpty) {
            _xifexpression_1 = "Model";
          } else {
            _xifexpression_1 = this.roots.get(0).getName();
          }
          this.rootName = _xifexpression_1;
          this.metamodelFileName = this.lastSegment(draw.getMetamodel());
          fsa.generateFile(
            ((("mutator/" + this.className) + "/") + this.fileName), 
            JavaUtils.format(this.compile(draw), false));
          index++;
        }
      }
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  public CharSequence compile(final MutatorDraw draw) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package mutator.");
    _builder.append(this.className);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.io.BufferedReader;");
    _builder.newLine();
    _builder.append("import java.io.File;");
    _builder.newLine();
    _builder.append("import java.io.IOException;");
    _builder.newLine();
    _builder.append("import java.lang.reflect.InvocationTargetException;");
    _builder.newLine();
    _builder.append("import java.net.URISyntaxException;");
    _builder.newLine();
    _builder.append("import java.nio.charset.StandardCharsets;");
    _builder.newLine();
    _builder.append("import java.nio.file.Files;");
    _builder.newLine();
    _builder.append("import java.nio.file.Path;");
    _builder.newLine();
    _builder.append("import java.util.Collections;");
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("import java.util.concurrent.TimeUnit;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import org.eclipse.core.commands.AbstractHandler;");
    _builder.newLine();
    _builder.append("import org.eclipse.core.commands.ExecutionEvent;");
    _builder.newLine();
    _builder.append("import org.eclipse.core.commands.ExecutionException;");
    _builder.newLine();
    _builder.append("import org.eclipse.core.resources.IProject;");
    _builder.newLine();
    _builder.append("import org.eclipse.core.runtime.IProgressMonitor;");
    _builder.newLine();
    _builder.append("import org.eclipse.core.runtime.NullProgressMonitor;");
    _builder.newLine();
    _builder.append("import org.eclipse.core.runtime.Platform;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.ecore.EObject;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.ecore.EPackage;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.ecore.resource.Resource;");
    _builder.newLine();
    _builder.append("import org.eclipse.jface.dialogs.ProgressMonitorDialog;");
    _builder.newLine();
    _builder.append("import org.eclipse.jface.operation.IRunnableWithProgress;");
    _builder.newLine();
    _builder.append("import org.eclipse.swt.widgets.Shell;");
    _builder.newLine();
    _builder.append("import org.eclipse.ui.handlers.HandlerUtil;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import wodel.utils.exceptions.MetaModelNotFoundException;");
    _builder.newLine();
    _builder.append("import wodel.utils.exceptions.ModelNotFoundException;");
    _builder.newLine();
    _builder.append("import wodel.utils.manager.ModelManager;");
    _builder.newLine();
    _builder.append("import wodel.utils.manager.ProjectUtils;");
    _builder.newLine();
    _builder.append("import wodel.utils.manager.Py2Code;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(this.className);
    _builder.append("Draw extends AbstractHandler");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("implements wodeledu.extension.run.commands.IMutatorDraw {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private static final String MODEL_EXTENSION = \".model\";");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private static final String ECORE_EXTENSION = \".ecore\";");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private static final String ROOT_NAME = \"");
    String _javaString = this.javaString(this.rootName);
    _builder.append(_javaString, "    ");
    _builder.append("\";");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("private static final String METAMODEL_FILE_NAME = \"");
    String _javaString_1 = this.javaString(this.metamodelFileName);
    _builder.append(_javaString_1, "    ");
    _builder.append("\";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("/*");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* Reuse the generic Model-Draw renderer preference when it happens");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* to identify a pygmentize executable or a directory containing it.");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("* Otherwise pygmentize is resolved from PATH.");
    _builder.newLine();
    _builder.append("     ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private static final String RENDERER_PLUGIN_ID = \"wodeledu.dsls.EduTest\";");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private static final String RENDERER_PREFERENCE = \"Model-Draw renderer path\";");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private static final class ProjectFolders {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("final File modelDirectory;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("final File mutantDirectory;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("ProjectFolders(File modelDirectory, File mutantDirectory) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("this.modelDirectory = modelDirectory;");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("this.mutantDirectory = mutantDirectory;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private final class RunMutatorPyCodeWithProgress");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("implements IRunnableWithProgress {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("public void run(IProgressMonitor monitor)");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("throws InvocationTargetException, InterruptedException {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("generate(monitor);");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("catch (InterruptedException e) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("Thread.currentThread().interrupt();");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("throw e;");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("catch (Exception e) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("throw new InvocationTargetException(e);");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private File resolveProjectDirectory() throws IOException {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("File location = new File(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append(this.className, "                    ");
    _builder.append("Draw.class");
    _builder.newLineIfNotEmpty();
    _builder.append("                        ");
    _builder.append(".getProtectionDomain()");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append(".getCodeSource()");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append(".getLocation()");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append(".toURI()");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (location.isFile()) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("location = location.getParentFile();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (location != null && \"bin\".equals(location.getName())) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("location = location.getParentFile();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("else if (location != null");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("&& \"classes\".equals(location.getName())");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("&& location.getParentFile() != null");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("&& \"target\".equals(location.getParentFile().getName())) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("location = location.getParentFile().getParentFile();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (location != null && location.isDirectory()) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("return location.getCanonicalFile();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("catch (URISyntaxException e) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("// Fall through to the Eclipse workspace lookup below.");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("IProject project = ProjectUtils.getProject();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (project != null && project.getLocation() != null) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return project.getLocation().toFile().getCanonicalFile();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new IOException(");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"Cannot determine the Wodel-EDU project directory for \"");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("+ ");
    _builder.append(this.className, "                ");
    _builder.append("Draw.class.getName()");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private ProjectFolders readProjectFolders(File projectDirectory)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throws IOException {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("File configFile = new File(");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("projectDirectory,");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"data/config/config.txt\"");
    _builder.newLine();
    _builder.append("        ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (!configFile.isFile()) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw new IOException(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("\"Cannot find Wodel configuration file: \" + configFile");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("try (BufferedReader reader = Files.newBufferedReader(");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("configFile.toPath(),");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("StandardCharsets.UTF_8");
    _builder.newLine();
    _builder.append("        ");
    _builder.append(")) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("String modelFolder = reader.readLine();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("String mutantFolder = reader.readLine();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (modelFolder == null || modelFolder.isBlank()");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("|| mutantFolder == null || mutantFolder.isBlank()) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("throw new IOException(");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("\"Invalid Wodel configuration file: \" + configFile");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return new ProjectFolders(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("new File(projectDirectory, modelFolder).getCanonicalFile(),");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("new File(projectDirectory, mutantFolder).getCanonicalFile()");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private File resolveMetamodelFile(File modelDirectory)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throws IOException {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (METAMODEL_FILE_NAME != null");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("&& !METAMODEL_FILE_NAME.isBlank()) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("File expected = new File(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("modelDirectory,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("METAMODEL_FILE_NAME");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (expected.isFile()) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("return expected;");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("File[] files = modelDirectory.listFiles();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (files != null) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("for (File file : files) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("if (file.isFile()");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("&& file.getName().endsWith(ECORE_EXTENSION)) {");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("return file;");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("throw new IOException(");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"Cannot find an Ecore metamodel in \" + modelDirectory");
    _builder.newLine();
    _builder.append("        ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String resolvePygmentizeExecutable() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("String rendererPath = Platform.getPreferencesService().getString(");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("RENDERER_PLUGIN_ID,");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("RENDERER_PREFERENCE,");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"\",");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("null");
    _builder.newLine();
    _builder.append("        ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (rendererPath != null && !rendererPath.isBlank()) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("File configured = new File(rendererPath).getAbsoluteFile();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (configured.isFile()) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("String name = configured.getName().toLowerCase();");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("if (name.startsWith(\"pygmentize\")) {");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("return configured.getAbsolutePath();");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (configured.isDirectory()) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("String executableName = isWindows()");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("? \"pygmentize.exe\"");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append(": \"pygmentize\";");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("File executable = new File(");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("configured,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("executableName");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("if (executable.isFile()) {");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("return executable.getAbsolutePath();");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("String systemProperty = System.getProperty(\"wodel.pygmentize\");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (systemProperty != null && !systemProperty.isBlank()) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return systemProperty;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("String environment = System.getenv(\"WODEL_PYGMENTIZE\");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (environment != null && !environment.isBlank()) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return environment;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return isWindows() ? \"pygmentize.exe\" : \"pygmentize\";");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private boolean isWindows() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return System.getProperty(\"os.name\", \"\")");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".toLowerCase()");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(".contains(\"win\");");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private void renderHighlightedHtml(");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("File pythonFile,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("File htmlFile,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("File workingDirectory,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("IProgressMonitor monitor)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throws IOException, InterruptedException {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("checkCanceled(monitor);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("ProcessBuilder processBuilder = new ProcessBuilder(");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("resolvePygmentizeExecutable(),");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"-O\",");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"full,style=emacs,linenos=1\",");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"-o\",");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("htmlFile.getAbsolutePath(),");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("pythonFile.getAbsolutePath()");
    _builder.newLine();
    _builder.append("        ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("processBuilder.directory(workingDirectory);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("processBuilder.redirectError(ProcessBuilder.Redirect.INHERIT);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("processBuilder.redirectOutput(ProcessBuilder.Redirect.INHERIT);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Process process;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("process = processBuilder.start();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("catch (IOException e) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw new IOException(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("\"Cannot start Pygments \'pygmentize\'. \"");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("+ \"Install Pygments or configure the Model-Draw renderer path. \"");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("+ \"Resolved command: \"");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("+ resolvePygmentizeExecutable(),");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("e");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("while (!process.waitFor(200, TimeUnit.MILLISECONDS)) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("checkCanceled(monitor);");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("int exitCode = process.exitValue();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (exitCode != 0) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("throw new IOException(");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("\"Pygments failed with exit code \" + exitCode");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("+ \" while rendering \" + pythonFile");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("catch (InterruptedException e) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (process.isAlive()) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("process.destroyForcibly();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("Thread.currentThread().interrupt();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw e;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (!htmlFile.isFile()) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw new IOException(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("\"Pygments completed without creating HTML output: \"");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("+ htmlFile");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private void renderModel(");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("File modelFile,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("List<EPackage> packages,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("File outputDirectory,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("File projectDirectory,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("IProgressMonitor monitor,");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("boolean mutant)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throws MetaModelNotFoundException,");
    _builder.newLine();
    _builder.append("                   ");
    _builder.append("ModelNotFoundException,");
    _builder.newLine();
    _builder.append("                   ");
    _builder.append("IOException,");
    _builder.newLine();
    _builder.append("                   ");
    _builder.append("InterruptedException {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (modelFile == null");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("|| !modelFile.isFile()");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("|| !modelFile.getName().endsWith(MODEL_EXTENSION)) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("checkCanceled(monitor);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("ensureDirectory(outputDirectory);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("String displayPath = safeRelativize(");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("projectDirectory.toPath().toAbsolutePath().normalize(),");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("modelFile.toPath().toAbsolutePath().normalize()");
    _builder.newLine();
    _builder.append("        ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("monitor.subTask(");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"Generating Python code for \"");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("+ (mutant ? \"mutant \" : \"model \")");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("+ displayPath");
    _builder.newLine();
    _builder.append("        ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Resource model = null;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("model = ModelManager.loadModel(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("packages,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("modelFile.getAbsolutePath()");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("EObject root = ModelManager.getRoot(model);");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (root == null) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("throw new IOException(");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("\"Cannot determine model root for \" + modelFile");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("String program = Py2Code.toPython(root);");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (program == null) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("throw new IOException(");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("\"Python code generation returned null for \" + modelFile");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("String outputBaseName = ROOT_NAME");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("+ \"_\"");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("+ stripExtension(modelFile.getName());");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("File pythonFile = new File(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("outputDirectory,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("outputBaseName + \".py\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("File htmlFile = new File(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("outputDirectory,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("outputBaseName + \".html\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("Files.writeString(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("pythonFile.toPath(),");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("program,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("StandardCharsets.UTF_8");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("renderHighlightedHtml(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("pythonFile,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("htmlFile,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("outputDirectory,");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("monitor");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("monitor.worked(1);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("finally {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (model != null && model.isLoaded()) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("model.unload();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void generate(IProgressMonitor progressMonitor)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throws MetaModelNotFoundException,");
    _builder.newLine();
    _builder.append("                   ");
    _builder.append("ModelNotFoundException,");
    _builder.newLine();
    _builder.append("                   ");
    _builder.append("IOException,");
    _builder.newLine();
    _builder.append("                   ");
    _builder.append("InterruptedException {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("IProgressMonitor monitor = progressMonitor != null");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("? progressMonitor");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(": new NullProgressMonitor();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("File projectDirectory = resolveProjectDirectory();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("ProjectFolders folders = readProjectFolders(projectDirectory);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("File metamodelFile = resolveMetamodelFile(folders.modelDirectory);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("File codeDirectory = new File(");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("projectDirectory,");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"src-gen/html/code\"");
    _builder.newLine();
    _builder.append("        ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("ensureDirectory(codeDirectory);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("List<EPackage> packages =");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("ModelManager.loadMetaModel(metamodelFile.getAbsolutePath());");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("List<String> models = ModelManager.getModels(");
    _builder.append(this.className, "        ");
    _builder.append("Draw.class);");
    _builder.newLineIfNotEmpty();
    _builder.append("        ");
    _builder.append("List<String> mutants = ModelManager.getMutants(");
    _builder.append(this.className, "        ");
    _builder.append("Draw.class);");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (models == null) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("models = Collections.emptyList();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (mutants == null) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("mutants = Collections.emptyList();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("monitor.beginTask(");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("\"Generating Python code\",");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("models.size() + mutants.size()");
    _builder.newLine();
    _builder.append("        ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("for (String modelPath : models) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("checkCanceled(monitor);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append("File modelFile = new File(modelPath);");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("File outputDirectory = new File(");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("codeDirectory,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("stripExtension(modelFile.getName())");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append("renderModel(");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("modelFile,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("packages,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("outputDirectory,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("projectDirectory,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("monitor,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("false");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("Path mutantRoot = folders.mutantDirectory");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append(".toPath()");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append(".toAbsolutePath()");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append(".normalize();");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("for (String mutantPath : mutants) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("checkCanceled(monitor);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append("File mutantFile = new File(mutantPath);");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("File parentFile = mutantFile.getParentFile();");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("Path parent = parentFile != null");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("? parentFile.toPath().toAbsolutePath().normalize()");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append(": mutantRoot;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append("String relative = safeRelativize(");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("mutantRoot,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("parent");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(");");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append("File outputDirectory = relative.isEmpty()");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("? codeDirectory");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append(": new File(codeDirectory, relative);");
    _builder.newLine();
    _builder.newLine();
    _builder.append("                ");
    _builder.append("renderModel(");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("mutantFile,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("packages,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("outputDirectory,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("projectDirectory,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("monitor,");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("true");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("finally {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("monitor.done();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String safeRelativize(Path root, Path child) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (root == null || child == null) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return \"\";");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("if (!child.startsWith(root)) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("return \"\";");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("            ");
    _builder.append("String relative = root.relativize(child).toString();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return relative.replace(\'\\\\\', \'/\');");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("catch (IllegalArgumentException e) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return \"\";");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String stripExtension(String name) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (name == null) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return \"\";");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("int dot = name.lastIndexOf(\'.\');");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return dot > 0 ? name.substring(0, dot) : name;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private void ensureDirectory(File directory) throws IOException {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (directory.isDirectory()) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (!directory.mkdirs() && !directory.isDirectory()) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw new IOException(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("\"Cannot create directory: \" + directory");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private void checkCanceled(IProgressMonitor monitor)");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throws InterruptedException {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (monitor != null && monitor.isCanceled()) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw new InterruptedException(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("\"Python-code generation was canceled\"");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public Object execute(ExecutionEvent event) throws ExecutionException {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("Shell shell = event != null");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("? HandlerUtil.getActiveShell(event)");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(": null;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("if (shell == null || shell.isDisposed()) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("generate(new NullProgressMonitor());");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("catch (InterruptedException e) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("Thread.currentThread().interrupt();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("catch (Exception e) {");
    _builder.newLine();
    _builder.append("                ");
    _builder.append("throw new ExecutionException(");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("\"Error generating Wodel-EDU Python code\",");
    _builder.newLine();
    _builder.append("                        ");
    _builder.append("e");
    _builder.newLine();
    _builder.append("                ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("return null;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("ProgressMonitorDialog dialog = new ProgressMonitorDialog(shell);");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("dialog.run(true, true, new RunMutatorPyCodeWithProgress());");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("catch (InvocationTargetException e) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("Throwable cause = e.getCause() != null");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("? e.getCause()");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append(": e;");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw new ExecutionException(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("\"Error generating Wodel-EDU Python code\",");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("cause");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("catch (InterruptedException e) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("Thread.currentThread().interrupt();");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return null;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("@Override");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void run() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("/*");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("* Non-UI extension entry point used reflectively by Wodel.");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("* Wodel may already be running inside a background progress");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("* operation, so never create a nested UI dialog here.");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("*/");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("try {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("generate(new NullProgressMonitor());");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("catch (InterruptedException e) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("Thread.currentThread().interrupt();");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw new IllegalStateException(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("\"Python-code generation was interrupted\",");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("e");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("catch (Exception e) {");
    _builder.newLine();
    _builder.append("            ");
    _builder.append("throw new IllegalStateException(");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("\"Error generating Wodel-EDU Python code\",");
    _builder.newLine();
    _builder.append("                    ");
    _builder.append("e");
    _builder.newLine();
    _builder.append("            ");
    _builder.append(");");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }
}
