/*
 * generated by Xtext
 */
package wodeledu.dsls;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MutaTextUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return wodeledu.dsls.ui.internal.MutaTextActivator.getInstance().getInjector("wodeledu.dsls.MutaText");
	}
	
}
