/**
 *
 * $Id$
 */
package mutatorenvironment.miniOCL.validation;

import mutatorenvironment.miniOCL.ExpCS;
import mutatorenvironment.miniOCL.PathNameCS;

/**
 * A sample validator interface for {@link mutatorenvironment.miniOCL.AccVarCS}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AccVarCSValidator {
	boolean validate();

	boolean validateAccVarName(String value);
	boolean validateAccType(PathNameCS value);
	boolean validateAccInitExp(ExpCS value);
}
