/**
 *
 * $Id$
 */
package mutatorenvironment.miniOCL.validation;

import mutatorenvironment.miniOCL.OperationCS;
import mutatorenvironment.miniOCL.PathNameCS;
import mutatorenvironment.miniOCL.PropertyCS;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mutatorenvironment.miniOCL.ClassCS}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ClassCSValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateExtends(PathNameCS value);
	boolean validateProperties(EList<PropertyCS> value);
	boolean validateOperations(EList<OperationCS> value);
}
