/**
 *
 * $Id$
 */
package mutatorenvironment.miniOCL.validation;

import mutatorenvironment.miniOCL.ExpCS;
import mutatorenvironment.miniOCL.IteratorVarCS;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mutatorenvironment.miniOCL.LoopExpCS}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoopExpCSValidator {
	boolean validate();

	boolean validateItVar(IteratorVarCS value);
	boolean validateLogicOp(EList<String> value);
	boolean validateExp(EList<ExpCS> value);
}
