/**
 *
 * $Id$
 */
package mutatorenvironment.miniOCL.validation;

import mutatorenvironment.miniOCL.CallExpCS;
import mutatorenvironment.miniOCL.NavigationPathNameCS;
import mutatorenvironment.miniOCL.RoundedBracketClauseCS;

/**
 * A sample validator interface for {@link mutatorenvironment.miniOCL.NavigationNameExpCS}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NavigationNameExpCSValidator {
	boolean validate();

	boolean validateExpName(NavigationPathNameCS value);
	boolean validateRoundedBrackets(RoundedBracketClauseCS value);
	boolean validateCallExp(CallExpCS value);
}
