/**
 *
 * $Id$
 */
package mutatorenvironment.miniOCL.validation;

import mutatorenvironment.miniOCL.ClassCS;
import mutatorenvironment.miniOCL.PackageCS;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mutatorenvironment.miniOCL.PackageCS}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageCSValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validatePackages(EList<PackageCS> value);
	boolean validateClasses(EList<ClassCS> value);
}
