/**
 *
 * $Id$
 */
package mutatorenvironment.miniOCL.validation;

import mutatorenvironment.miniOCL.ConstraintCS;
import mutatorenvironment.miniOCL.PackageCS;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link mutatorenvironment.miniOCL.RootCS}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RootCSValidator {
	boolean validate();

	boolean validatePackages(EList<PackageCS> value);
	boolean validateContraints(EList<ConstraintCS> value);
}
