/*
 * generated by Xtext
 */
package wodeledu.dsls.ui.contentassist

import wodeledu.dsls.ui.contentassist.AbstractModelTextProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ModelTextProposalProvider extends AbstractModelTextProposalProvider {
}
