/*
 * generated by Xtext
 */
package wodel.dsls.ui;

import manager.MutatorChangeListener;

import org.eclipse.core.resources.IResourceChangeEvent;
import org.eclipse.core.resources.IResourceChangeListener;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * @author Pablo Gomez-Abajo - Wodel UI Module
 * 
 * Wodel User Interface contributions.
 *
 */
public class WodelUiModule extends wodel.dsls.ui.AbstractWodelUiModule {
	public WodelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
		IResourceChangeListener listener = new MutatorChangeListener();
		ResourcesPlugin.getWorkspace().addResourceChangeListener(listener, IResourceChangeEvent.POST_CHANGE);
	}
	public Class<? extends org.eclipse.xtext.ui.editor.preferences.LanguageRootPreferencePage> bindLanguageRootPreferencePage() {
	    return wodel.dsls.ui.customize.WodelGeneralPreferencePage.class;
	}
}
