/**
 * generated by Xtext 2.13.0
 */
package wodeledu.dsls.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import wodeledu.dsls.MutaTextRuntimeModule;
import wodeledu.dsls.MutaTextStandaloneSetup;
import wodeledu.dsls.ide.MutaTextIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MutaTextIdeSetup extends MutaTextStandaloneSetup {
  @Override
  public Injector createInjector() {
    MutaTextRuntimeModule _mutaTextRuntimeModule = new MutaTextRuntimeModule();
    MutaTextIdeModule _mutaTextIdeModule = new MutaTextIdeModule();
    return Guice.createInjector(Modules2.mixin(_mutaTextRuntimeModule, _mutaTextIdeModule));
  }
}
