/*
 * generated by Xtext
 */
package org.mutatortests;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TestsStandaloneSetup extends TestsStandaloneSetupGenerated{

	public static void doSetup() {
		new TestsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

