/*
 * generated by Xtext
 */
package org.mutatorgraph.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MutatorGraphUiModule extends org.mutatorgraph.ui.AbstractMutatorGraphUiModule {
	public MutatorGraphUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
