/*
 * generated by Xtext
 */
package wodel.dsls.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import wodel.dsls.services.AspleGrammarAccess;

public class AspleParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AspleGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected wodel.dsls.parser.antlr.internal.InternalAspleParser createParser(XtextTokenStream stream) {
		return new wodel.dsls.parser.antlr.internal.InternalAspleParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public AspleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AspleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
