/**
 * generated by Xtext
 */
package wodel.dsls.serializer;

import wodel.dsls.serializer.AbstractWodelSyntacticSequencer;

@SuppressWarnings("all")
public class WodelSyntacticSequencer extends AbstractWodelSyntacticSequencer {
}
