/*
 * generated by Xtext
 */
package wodel.dsls;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AspleRuntimeModule extends wodel.dsls.AbstractAspleRuntimeModule {

}
