/**
 * generated by Xtext 2.13.0
 */
package wodeledu.dsls.ui.contentassist;

import wodeledu.dsls.ui.contentassist.AbstractEduTestProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EduTestProposalProvider extends AbstractEduTestProposalProvider {
}
