/*
 * generated by Xtext
 */
package wodeledu.dsls;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MutaTextStandaloneSetup extends MutaTextStandaloneSetupGenerated{

	public static void doSetup() {
		new MutaTextStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

