/**
 * generated by Xtext 2.13.0
 */
package wodel.dsls.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import wodel.dsls.WodelRuntimeModule;
import wodel.dsls.WodelStandaloneSetup;
import wodel.dsls.ide.WodelIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class WodelIdeSetup extends WodelStandaloneSetup {
  @Override
  public Injector createInjector() {
    WodelRuntimeModule _wodelRuntimeModule = new WodelRuntimeModule();
    WodelIdeModule _wodelIdeModule = new WodelIdeModule();
    return Guice.createInjector(Modules2.mixin(_wodelRuntimeModule, _wodelIdeModule));
  }
}
