/**
 * generated by Xtext 2.13.0
 */
package wodel.dsls.ide;

import wodel.dsls.ide.AbstractWodelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class WodelIdeModule extends AbstractWodelIdeModule {
}
