/**
 * generated by Xtext
 */
package org.identifyelements.validation;

import org.identifyelements.validation.AbstractIdentifyElementsValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IdentifyElementsValidator extends AbstractIdentifyElementsValidator {
}
