/*
 * generated by Xtext 2.36.0
 */
package wodeledu.dsls.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMutaTextScopeProvider extends DelegatingScopeProvider {
}
