/*
 * generated by Xtext 2.30.0
 */
package wodeledu.dsls.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

public abstract class AbstractMutaTextScopeProvider extends AbstractDeclarativeScopeProvider {
}
