/**
 * generated by Xtext 2.13.0
 */
package wodeledu.dsls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import wodeledu.dsls.ui.AbstractModelDrawUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ModelDrawUiModule extends AbstractModelDrawUiModule {
  public ModelDrawUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
