/*
 * generated by Xtext
 */
package org.mutator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MutatorRuntimeModule extends org.mutator.AbstractMutatorRuntimeModule {

}
