/**
 * generated by Xtext
 */
package org.configureoptions.serializer;

import org.configureoptions.serializer.AbstractConfigureOptionsSemanticSequencer;

@SuppressWarnings("all")
public class ConfigureOptionsSemanticSequencer extends AbstractConfigureOptionsSemanticSequencer {
}
