/**
 * generated by Xtext
 */
package org.configureoptions.serializer;

import org.configureoptions.serializer.AbstractConfigureOptionsSyntacticSequencer;

@SuppressWarnings("all")
public class ConfigureOptionsSyntacticSequencer extends AbstractConfigureOptionsSyntacticSequencer {
}
