package wodel.dsls.generator;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import mutatorenvironment.Definition;
import mutatorenvironment.MutatorEnvironment;
import mutatorenvironment.Program;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.Platform;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.xbase.lib.Exceptions;
import wodel.utils.manager.ModelManager;

/**
 * @author Pablo Gomez-Abajo - Wodel Java code generator.
 * 
 * Generates the code to programmatically execute the Wodel program.
 */
@SuppressWarnings("all")
public abstract class WodelAPIGenerator extends AbstractGenerator {
  protected URI fileURI;

  protected Program program;

  protected IProject project = null;

  protected String xmiFileName;

  protected boolean standalone = false;

  /**
   * Explicit project context used by semantic/XMI headless generation.
   */
  public void setGenerationProject(final IProject generationProject) {
    this.project = generationProject;
  }

  public static IProject projectOf(final Resource r) {
    Object _xblockexpression = null;
    {
      URI _uRI = null;
      if (r!=null) {
        _uRI=r.getURI();
      }
      final URI uri = _uRI;
      if (((uri != null) && uri.isPlatformResource())) {
        final String projectName = uri.segment(1);
        return ResourcesPlugin.getWorkspace().getRoot().getProject(projectName);
      }
      _xblockexpression = null;
    }
    return ((IProject)_xblockexpression);
  }

  public String getMutatorPath(final MutatorEnvironment e, final IProject project, final File[] files) {
    IProject p = WodelAPIGenerator.projectOf(e.eResource());
    IProject _xifexpression = null;
    if ((p != null)) {
      _xifexpression = p;
    } else {
      _xifexpression = project;
    }
    p = _xifexpression;
    String mutatorPath = null;
    if (((mutatorPath == null) && (files != null))) {
      for (final File file : files) {
        {
          if ((mutatorPath != null)) {
            return mutatorPath;
          }
          if ((file != null)) {
            if ((file.exists() && (file.isFile() == true))) {
              String path = file.getPath().replace("\\", "/");
              String _name = p.getName();
              String _plus = ("/" + _name);
              String _plus_1 = (_plus + "/");
              int _indexOf = path.indexOf(_plus_1);
              boolean _notEquals = (_indexOf != (-1));
              if (_notEquals) {
                String _name_1 = p.getName();
                String _plus_2 = ("/" + _name_1);
                String _plus_3 = (_plus_2 + "/");
                String mutatorFolderAndFile = path.substring(path.lastIndexOf(_plus_3));
                boolean _equals = mutatorFolderAndFile.equals(this.fileURI.toPlatformString(true));
                if (_equals) {
                  String _replace = p.getLocation().toFile().getPath().replace("\\", "/");
                  String _plus_4 = ("file:/" + _replace);
                  String _plus_5 = (_plus_4 + "/");
                  String _name_2 = p.getName();
                  String _plus_6 = ("/" + _name_2);
                  String _substring = mutatorFolderAndFile.substring((_plus_6 + "/").length());
                  String _plus_7 = (_plus_5 + _substring);
                  mutatorPath = _plus_7;
                }
              }
            }
            if ((file.exists() && file.isDirectory())) {
              mutatorPath = this.getMutatorPath(e, p, file.listFiles());
            }
          }
        }
      }
    }
    return mutatorPath;
  }

  public CharSequence compile(final MutatorEnvironment e, final IProject project, final String mutatorName, final String className) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("//");
    _builder.append(this.project = WodelAPIGenerator.projectOf(e.eResource()));
    _builder.newLineIfNotEmpty();
    _builder.append("//");
    IProject _xifexpression = null;
    if ((this.project != null)) {
      _xifexpression = this.project;
    } else {
      _xifexpression = project;
    }
    IProject _project = this.project = _xifexpression;
    _builder.append(_project);
    _builder.newLineIfNotEmpty();
    _builder.append("package mutator.");
    _builder.append(mutatorName);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.io.IOException;");
    _builder.newLine();
    _builder.append("import java.util.ArrayList;");
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.append("import java.util.Map;");
    _builder.newLine();
    _builder.append("import java.util.TreeMap;");
    _builder.newLine();
    _builder.append("import org.eclipse.core.resources.IProject;");
    _builder.newLine();
    _builder.append("import org.eclipse.core.runtime.IProgressMonitor;");
    _builder.newLine();
    _builder.append("import org.eclipse.core.runtime.NullProgressMonitor;");
    _builder.newLine();
    _builder.append("import org.eclipse.emf.ecore.EPackage;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import wodel.utils.exceptions.AbstractCreationException;");
    _builder.newLine();
    _builder.append("import wodel.utils.exceptions.MaxSmallerThanMinException;");
    _builder.newLine();
    _builder.append("import wodel.utils.exceptions.MetaModelNotFoundException;");
    _builder.newLine();
    _builder.append("import wodel.utils.exceptions.ModelNotFoundException;");
    _builder.newLine();
    _builder.append("import wodel.utils.exceptions.ObjectNoTargetableException;");
    _builder.newLine();
    _builder.append("import wodel.utils.exceptions.ObjectNotContainedException;");
    _builder.newLine();
    _builder.append("import wodel.utils.exceptions.ReferenceNonExistingException;");
    _builder.newLine();
    _builder.append("import wodel.utils.exceptions.WrongAttributeTypeException;");
    _builder.newLine();
    _builder.append("import wodel.utils.manager.ModelManager;");
    _builder.newLine();
    {
      if ((this.standalone == false)) {
        _builder.append("import mutator.");
        _builder.append(mutatorName);
        _builder.append("Dynamic.");
        _builder.append(mutatorName);
        _builder.append("Dynamic;");
        _builder.newLineIfNotEmpty();
        _builder.append("import wodel.utils.manager.IMutatorAPI;");
        _builder.newLine();
      } else {
        _builder.append("import mutator.");
        _builder.append(mutatorName);
        _builder.append("Standalone.");
        _builder.append(mutatorName);
        _builder.append("Standalone;");
        _builder.newLineIfNotEmpty();
        _builder.append("import org.eclipse.core.runtime.NullProgressMonitor;");
        _builder.newLine();
        _builder.append("import wodel.utils.manager.MutatorStandaloneAPI;");
        _builder.newLine();
      }
    }
    _builder.append("import wodel.utils.manager.MutatorUtils;");
    _builder.newLine();
    _builder.newLine();
    {
      if ((this.standalone == false)) {
        _builder.append("public class ");
        _builder.append(className);
        _builder.append(" implements IMutatorAPI {");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public static MutatorUtils.MutationResults createMutants(");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("String[] mutationOperators,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("IProject project,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("IProgressMonitor monitor)");
        _builder.newLine();
        _builder.append("\t    ");
        _builder.append("throws ReferenceNonExistingException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("WrongAttributeTypeException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("MaxSmallerThanMinException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("AbstractCreationException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ObjectNoTargetableException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ObjectNotContainedException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("MetaModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("IOException {");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("return createMutants(mutationOperators, project, monitor, System.nanoTime());");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("} ");
        _builder.newLine();
      } else {
        _builder.append("public class ");
        _builder.append(className);
        _builder.append(" extends MutatorStandaloneAPI {");
        _builder.newLineIfNotEmpty();
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public static MutatorUtils.MutationResults createMutants(");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("String[] mutationOperators,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("boolean registry)");
        _builder.newLine();
        _builder.append("\t    ");
        _builder.append("throws ReferenceNonExistingException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("WrongAttributeTypeException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("MaxSmallerThanMinException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("AbstractCreationException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ObjectNoTargetableException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ObjectNotContainedException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("MetaModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("IOException {");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("return createMutants(mutationOperators, registry, System.nanoTime());");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
      }
    }
    {
      if ((this.standalone == false)) {
        _builder.append("\t");
        _builder.append("public static MutatorUtils.MutationResults createMutants(");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("        ");
        _builder.append("String[] mutationOperators,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("        ");
        _builder.append("IProject project,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("        ");
        _builder.append("IProgressMonitor monitor,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("        ");
        _builder.append("long executionSeed)");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("    ");
        _builder.append("throws ReferenceNonExistingException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("WrongAttributeTypeException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("MaxSmallerThanMinException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("AbstractCreationException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("ObjectNoTargetableException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("ObjectNotContainedException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("MetaModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("ModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("IOException {");
        _builder.newLine();
      } else {
        _builder.append("\t");
        _builder.append("public static MutatorUtils.MutationResults createMutants(");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("        ");
        _builder.append("String[] mutationOperators,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("        ");
        _builder.append("boolean registry,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("        ");
        _builder.append("long executionSeed)");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("    ");
        _builder.append("throws ReferenceNonExistingException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("WrongAttributeTypeException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("MaxSmallerThanMinException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("AbstractCreationException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("ObjectNoTargetableException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("ObjectNotContainedException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("MetaModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("ModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("           ");
        _builder.append("IOException {");
        _builder.newLine();
      }
    }
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("System.out.println(\"Wodel mutator file: ");
    _builder.append(mutatorName, "\t\t");
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("String ecoreURI = \"");
    String _metaModel = ModelManager.getMetaModel(e);
    _builder.append(_metaModel, "\t\t");
    _builder.append("\";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("List<EPackage> packages = null;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("try {");
    _builder.newLine();
    {
      if ((this.standalone == false)) {
        _builder.append("\t\t\t");
        _builder.append("packages = ModelManager.loadMetaModel(\"");
        String _metaModel_1 = ModelManager.getMetaModel(e);
        _builder.append(_metaModel_1, "\t\t\t");
        _builder.append("\", ");
        _builder.append(className, "\t\t\t");
        _builder.append(".class);");
        _builder.newLineIfNotEmpty();
      } else {
        _builder.append("\t\t\t");
        _builder.append("packages = ModelManager.loadMetaModelNoException(\"");
        String _name = project.getName();
        _builder.append(_name, "\t\t\t");
        _builder.append("\", ecoreURI);");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("catch (Exception e) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("boolean isRegistered = ModelManager.isRegistered(packages);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Map<String, EPackage> registeredPackages = ModelManager.registeredMetaModels(packages);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("Map<String, EPackage> localRegisteredPackages = null;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("if (isRegistered == true) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (registeredPackages != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("List<EPackage> packageList = new ArrayList<EPackage>();");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("packageList.addAll(registeredPackages.values());");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("ModelManager.unregisterMetaModel(packageList);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("localRegisteredPackages = ModelManager.unregisterMetaModel(packages);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("//");
    int maxAttempts = 3;
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("//");
    int numMutants = 10;
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("//");
    boolean registry = true;
    _builder.newLineIfNotEmpty();
    _builder.append("            ");
    _builder.append("//");
    Boolean _xtrycatchfinallyexpression = null;
    try {
      boolean _xblockexpression = false;
      {
        maxAttempts = Integer.parseInt(Platform.getPreferencesService().getString("wodel.dsls.Wodel", "Number of attempts", "3", null));
        numMutants = Integer.parseInt(Platform.getPreferencesService().getString("wodel.dsls.Wodel", "Number of mutants", "3", null));
        _xblockexpression = registry = Platform.getPreferencesService().getBoolean("wodel.dsls.Wodel", "Generate registry", true, null);
      }
      _xtrycatchfinallyexpression = Boolean.valueOf(_xblockexpression);
    } catch (final Throwable _t) {
      if (_t instanceof Exception) {
        _xtrycatchfinallyexpression = null;
      } else {
        throw Exceptions.sneakyThrow(_t);
      }
    }
    _builder.append(_xtrycatchfinallyexpression, "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("int maxAttempts = ");
    _builder.append(maxAttempts, "\t\t");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("int numMutants = ");
    _builder.append(numMutants, "\t\t");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    {
      if ((this.standalone == false)) {
        _builder.append("\t\t");
        _builder.append("boolean registry = ");
        _builder.append(registry, "\t\t");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t\t");
    _builder.newLine();
    {
      if ((this.standalone == false)) {
        _builder.append("\t\t");
        _builder.append("//");
        boolean metrics = false;
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("//");
        boolean debugMetrics = false;
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("//");
        Boolean _xtrycatchfinallyexpression_1 = null;
        try {
          boolean _xblockexpression = false;
          {
            metrics = Platform.getPreferencesService().getBoolean("wodel.dsls.Wodel", "Generate net mutant footprints", false, null);
            _xblockexpression = debugMetrics = Platform.getPreferencesService().getBoolean("wodel.dsls.Wodel", "Generate debug mutant footprints", false, null);
          }
          _xtrycatchfinallyexpression_1 = Boolean.valueOf(_xblockexpression);
        } catch (final Throwable _t) {
          if (_t instanceof Exception) {
            _xtrycatchfinallyexpression_1 = null;
          } else {
            throw Exceptions.sneakyThrow(_t);
          }
        }
        _builder.append(_xtrycatchfinallyexpression_1, "\t\t");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("boolean metrics = ");
        _builder.append(metrics, "\t\t");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("boolean debugMetrics = ");
        _builder.append(debugMetrics, "\t\t");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("MutatorUtils mut");
        _builder.append(mutatorName, "\t\t");
        _builder.append(" =");
        _builder.newLineIfNotEmpty();
        {
          if ((this.standalone == false)) {
            _builder.append("\t\t");
            _builder.append("new ");
            _builder.append(mutatorName, "\t\t");
            _builder.append("Dynamic();");
            _builder.newLineIfNotEmpty();
          } else {
            _builder.append("\t\t");
            _builder.append("new ");
            _builder.append(mutatorName, "\t\t");
            _builder.append("Standalone();");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("\t\t");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("MutatorUtils.MutationResults mutationResults = null;");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("try {");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("    ");
        _builder.append("mutationResults = mut");
        _builder.append(mutatorName, "\t\t    ");
        _builder.append(".execute(");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("maxAttempts,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("numMutants,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("registry,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("metrics,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("debugMetrics,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("packages,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("registeredPackages,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("localRegisteredPackages,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("mutationOperators,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("new NullProgressMonitor(),");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("true,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("null,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("new TreeMap<String, List<String>>(),");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("executionSeed);");
        _builder.newLine();
      } else {
        _builder.append("\t\t");
        _builder.append("boolean metrics = false;");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("boolean debugMetrics = false;");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("MutatorUtils mut");
        _builder.append(mutatorName, "\t\t");
        _builder.append(" =");
        _builder.newLineIfNotEmpty();
        {
          if ((this.standalone == false)) {
            _builder.append("\t\t");
            _builder.append("new ");
            _builder.append(mutatorName, "\t\t");
            _builder.append("Dynamic();");
            _builder.newLineIfNotEmpty();
          } else {
            _builder.append("\t\t");
            _builder.append("new ");
            _builder.append(mutatorName, "\t\t");
            _builder.append("Standalone();");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("\t\t");
        _builder.append("MutatorUtils.MutationResults mutationResults = null;");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("try {");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("\t");
        _builder.append("mutationResults =");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("    ");
        _builder.append("mut");
        _builder.append(mutatorName, "\t\t    ");
        _builder.append(".execute(");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("maxAttempts,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("numMutants,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("registry,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("metrics,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("debugMetrics,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("packages,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("registeredPackages,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("localRegisteredPackages,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("mutationOperators,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("new NullProgressMonitor(),");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("true,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("null,");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("new TreeMap<String, List<String>>(),");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("        ");
        _builder.append("executionSeed);");
        _builder.newLine();
      }
    }
    _builder.append("\t\t\t\t");
    _builder.append("}finally {");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("if (isRegistered == true) {");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("if (localRegisteredPackages != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t            ");
    _builder.append("ModelManager.registerMetaModel(");
    _builder.newLine();
    _builder.append("\t\t\t\t                ");
    _builder.append("localRegisteredPackages);");
    _builder.newLine();
    _builder.append("\t\t\t\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.newLine();
    _builder.append("\t\t\t\t        ");
    _builder.append("if (registeredPackages != null) {");
    _builder.newLine();
    _builder.append("\t\t\t\t            ");
    _builder.append("ModelManager.registerMetaModel(");
    _builder.newLine();
    _builder.append("\t\t\t\t                ");
    _builder.append("registeredPackages);");
    _builder.newLine();
    _builder.append("\t\t\t\t        ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.newLine();
    {
      if ((this.standalone == true)) {
        _builder.append("\t\t");
        _builder.append("System.out.println(");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("    ");
        _builder.append("\"");
        _builder.append(mutatorName, "\t\t    ");
        _builder.append(" Mutant generation process finished.\");");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t\t");
    _builder.append("return mutationResults;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  public CharSequence launcherDynamic(final MutatorEnvironment e, final IProject project, final List<String> mutators, final Map<String, List<String>> mutMap) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("//");
    _builder.append(this.project = WodelAPIGenerator.projectOf(e.eResource()), "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("//");
    IProject _xifexpression = null;
    if ((this.project != null)) {
      _xifexpression = this.project;
    } else {
      _xifexpression = project;
    }
    IProject _project = this.project = _xifexpression;
    _builder.append(_project, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("package mutator.");
    String _name = project.getName();
    _builder.append(_name);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("import java.util.ArrayList;");
    _builder.newLine();
    _builder.append("import java.util.List;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("import wodel.utils.manager.MutatorAPILauncher;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ");
    String _replaceAll = project.getName().replaceAll("[.]", "_");
    _builder.append(_replaceAll);
    _builder.append("DynamicAPILauncher {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public static void main(String[] args) ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("{");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("String ecoreURI = \"");
    String _metaModel = ModelManager.getMetaModel(e);
    _builder.append(_metaModel, "\t\t");
    _builder.append("\";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.append("List<String> mutatorNames = new ArrayList<String>();");
    _builder.newLine();
    {
      Set<String> _keySet = mutMap.keySet();
      for(final String mutatorName : _keySet) {
        _builder.append("\t\t");
        _builder.append("mutatorNames.add(\"");
        _builder.append(mutatorName, "\t\t");
        _builder.append("\");");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t\t");
    _builder.append("List<List<String>> operatorNames = new ArrayList<List<String>>();");
    _builder.newLine();
    {
      Set<String> _keySet_1 = mutMap.keySet();
      for(final String mut : _keySet_1) {
        _builder.append("\t\t");
        _builder.append("List<String> mutatorOperatorNames");
        _builder.append(mut, "\t\t");
        _builder.append(" = new ArrayList<String>();");
        _builder.newLineIfNotEmpty();
        {
          List<String> _get = mutMap.get(mut);
          for(final String operator : _get) {
            _builder.append("\t\t");
            _builder.append("mutatorOperatorNames");
            _builder.append(mut, "\t\t");
            _builder.append(".add(\"");
            _builder.append(operator, "\t\t");
            _builder.append("\");");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("\t\t");
        _builder.append("operatorNames.add(mutatorOperatorNames");
        _builder.append(mut, "\t\t");
        _builder.append(");");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("\t\t");
    _builder.append("String[] arrMutatorNames = new String[mutatorNames.size()];");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("mutatorNames.toArray(arrMutatorNames);");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("String[][] arrOperatorNames = new String[mutatorNames.size()][];");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("int i = 0;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("for (List<String> mutOpNames : operatorNames) {");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("String[] arrMutatorOperatorNames = new String[mutOpNames.size()];");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("mutOpNames.toArray(arrMutatorOperatorNames);");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("arrOperatorNames[i] = arrMutatorOperatorNames;");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("i++;");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("MutatorAPILauncher.createMutants(\"");
    String _name_1 = project.getName();
    _builder.append(_name_1, "\t\t");
    _builder.append("\", ecoreURI, ");
    String _replaceAll_1 = project.getName().replaceAll("[.]", "_");
    _builder.append(_replaceAll_1, "\t\t");
    _builder.append("APILauncher.class, arrMutatorNames, arrOperatorNames, \"D:\\\\seed\", \"D:\\\\mutants\");");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  public String resolveMetaModelPath(final EObject metaModel, final IProject project) {
    if ((metaModel instanceof MutatorEnvironment)) {
      final MutatorEnvironment mut = ((MutatorEnvironment) metaModel);
      Definition _definition = mut.getDefinition();
      if ((_definition instanceof Program)) {
        Definition _definition_1 = mut.getDefinition();
        final Program program = ((Program) _definition_1);
        final String value = program.getMetamodel().replace("\\", "/");
        final String projectRoot = project.getLocation().toFile().getAbsolutePath().replace("\\", "/");
        boolean _matches = value.matches("^[A-Za-z]:/.*");
        if (_matches) {
          return value;
        }
        String _name = project.getName();
        String _plus = ("platform:/resource/" + _name);
        final String platformPrefix = (_plus + "/");
        boolean _startsWith = value.startsWith(platformPrefix);
        if (_startsWith) {
          String _substring = value.substring(platformPrefix.length());
          return ((projectRoot + "/") + _substring);
        }
        String _name_1 = project.getName();
        String _plus_1 = ("/" + _name_1);
        final String projectPrefix = (_plus_1 + "/");
        boolean _startsWith_1 = value.startsWith(projectPrefix);
        if (_startsWith_1) {
          String _substring_1 = value.substring(projectPrefix.length());
          return ((projectRoot + "/") + _substring_1);
        }
        boolean _startsWith_2 = value.startsWith("/");
        boolean _not = (!_startsWith_2);
        if (_not) {
          return ((projectRoot + "/") + value);
        }
        return value;
      }
    }
    return null;
  }

  public CharSequence launcherStandalone(final List<MutatorEnvironment> mutEnvironment, final IProject project, final Map<String, List<String>> mutMap) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    {
      if (((mutEnvironment != null) && (!mutEnvironment.isEmpty()))) {
        _builder.newLine();
        _builder.append("\t");
        _builder.append("//");
        _builder.append(this.project = WodelAPIGenerator.projectOf(mutEnvironment.get(0).eResource()), "\t");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("//");
        IProject _xifexpression = null;
        if ((this.project != null)) {
          _xifexpression = this.project;
        } else {
          _xifexpression = project;
        }
        IProject _project = this.project = _xifexpression;
        _builder.append(_project, "\t");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("//");
        String _replaceAll = project.getName().replaceAll("[.]", "_");
        String className = (_replaceAll + "StandaloneAPILauncher");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("package mutator.");
        String _name = project.getName();
        _builder.append(_name);
        _builder.append(";");
        _builder.newLineIfNotEmpty();
        _builder.newLine();
        _builder.append("import java.util.ArrayList;");
        _builder.newLine();
        _builder.append("import java.util.List;");
        _builder.newLine();
        _builder.newLine();
        _builder.append("import wodel.utils.exceptions.AbstractCreationException;");
        _builder.newLine();
        _builder.append("import wodel.utils.exceptions.MaxSmallerThanMinException;");
        _builder.newLine();
        _builder.append("import wodel.utils.exceptions.MetaModelNotFoundException;");
        _builder.newLine();
        _builder.append("import wodel.utils.exceptions.ModelNotFoundException;");
        _builder.newLine();
        _builder.append("import wodel.utils.exceptions.ObjectNoTargetableException;");
        _builder.newLine();
        _builder.append("import wodel.utils.exceptions.ObjectNotContainedException;");
        _builder.newLine();
        _builder.append("import wodel.utils.exceptions.ReferenceNonExistingException;");
        _builder.newLine();
        _builder.append("import wodel.utils.exceptions.WrongAttributeTypeException;");
        _builder.newLine();
        _builder.append("import java.io.IOException;");
        _builder.newLine();
        _builder.append("import java.io.File;");
        _builder.newLine();
        _builder.append("import wodel.utils.manager.IOUtils;");
        _builder.newLine();
        _builder.append("import wodel.utils.manager.MutatorUtils;");
        _builder.newLine();
        _builder.append("import wodel.utils.manager.ModelManager;");
        _builder.newLine();
        _builder.newLine();
        _builder.append("import java.nio.file.DirectoryStream;");
        _builder.newLine();
        _builder.append("import java.nio.file.Files;");
        _builder.newLine();
        _builder.append("import java.nio.file.Path;");
        _builder.newLine();
        _builder.append("import java.nio.file.Paths;");
        _builder.newLine();
        _builder.newLine();
        _builder.append("import org.eclipse.emf.ecore.EPackage;");
        _builder.newLine();
        _builder.newLine();
        _builder.newLine();
        {
          Set<String> _keySet = mutMap.keySet();
          for(final String mutatorName : _keySet) {
            _builder.append("import mutator.");
            _builder.append(mutatorName);
            _builder.append(".");
            _builder.append(mutatorName);
            _builder.append("StandaloneAPI;");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.newLine();
        _builder.append("public class ");
        String _replaceAll_1 = project.getName().replaceAll("[.]", "_");
        _builder.append(_replaceAll_1);
        _builder.append("StandaloneAPILauncher {");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("public static boolean registerMetaModel(List<EPackage> packages) {");
        _builder.newLine();
        _builder.append("\t\t\t");
        _builder.append("if (packages == null) {");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.append("return false;");
        _builder.newLine();
        _builder.append("\t\t\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t\t\t");
        _builder.append("for (EPackage pck : packages) {");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.append("EPackage.Registry.INSTANCE.put(pck.getNsURI(), pck);");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.append("if (pck.getESubpackages() != null && !pck.getESubpackages().isEmpty()) {");
        _builder.newLine();
        _builder.append("\t\t\t\t\t");
        _builder.append("registerMetaModel(pck.getESubpackages());");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t\t\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t\t\t");
        _builder.append("return true;");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.append("private static void merge(");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("MutatorUtils.MutationResults target,");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("MutatorUtils.MutationResults source) {");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t    ");
        _builder.append("if (source == null) {");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("return;");
        _builder.newLine();
        _builder.append("\t\t\t\t    ");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t    ");
        _builder.append("target.setNumMutatorsApplied(");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("target.getNumMutatorsApplied()");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("+ source.getNumMutatorsApplied());");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t    ");
        _builder.append("target.setNumMutantsGenerated(");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("target.getNumMutantsGenerated()");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("+ source.getNumMutantsGenerated());");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t    ");
        _builder.append("if (source.getMutatorsApplied() != null) {");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("List<String> applied =");
        _builder.newLine();
        _builder.append("\t\t\t\t            ");
        _builder.append("target.getMutatorsApplied();");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("if (applied == null) {");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t            ");
        _builder.append("applied =");
        _builder.newLine();
        _builder.append("\t\t\t\t                ");
        _builder.append("new ArrayList<String>();");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t            ");
        _builder.append("target.setMutatorsApplied(");
        _builder.newLine();
        _builder.append("\t\t\t\t                ");
        _builder.append("applied);");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("applied.addAll(");
        _builder.newLine();
        _builder.append("\t\t\t\t            ");
        _builder.append("source.getMutatorsApplied());");
        _builder.newLine();
        _builder.append("\t\t\t\t    ");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.append("public static List<String> getAllOperatorNames() {");
        _builder.newLine();
        _builder.append("\t\t\t\t\t");
        _builder.append("//");
        List<String> mutMapKeyList = new ArrayList<String>();
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t\t\t\t");
        _builder.append("//");
        boolean _addAll = mutMapKeyList.addAll(mutMap.keySet());
        _builder.append(_addAll, "\t\t\t\t\t");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t\t\t\t ");
        _builder.append("return List.of(");
        _builder.newLine();
        _builder.append("\t\t\t\t\t\t\t\t\t");
        _builder.newLine();
        {
          int _size = mutMap.keySet().size();
          int _minus = (_size - 1);
          List<String> _subList = mutMapKeyList.subList(0, _minus);
          for(final String mut : _subList) {
            {
              List<String> _get = mutMap.get(mut);
              for(final String operator : _get) {
                _builder.append("\"");
                _builder.append(operator);
                _builder.append("\",");
                _builder.newLineIfNotEmpty();
              }
            }
          }
        }
        _builder.append("\t\t\t\t\t    ");
        _builder.newLine();
        {
          int _size_1 = mutMapKeyList.size();
          int _minus_1 = (_size_1 - 1);
          List<String> _get_1 = mutMap.get(mutMapKeyList.get(_minus_1));
          int _size_2 = mutMapKeyList.size();
          int _minus_2 = (_size_2 - 1);
          int _size_3 = mutMap.get(mutMapKeyList.get(_minus_2)).size();
          int _minus_3 = (_size_3 - 1);
          List<String> _subList_1 = _get_1.subList(0, _minus_3);
          for(final String operator_1 : _subList_1) {
            _builder.append("\"");
            _builder.append(operator_1);
            _builder.append("\",");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("\t\t\t\t\t\t");
        _builder.append("\"");
        int _size_4 = mutMapKeyList.size();
        int _minus_4 = (_size_4 - 1);
        List<String> _get_2 = mutMap.get(mutMapKeyList.get(_minus_4));
        int _size_5 = mutMapKeyList.size();
        int _minus_5 = (_size_5 - 1);
        int _size_6 = mutMap.get(mutMapKeyList.get(_minus_5)).size();
        int _minus_6 = (_size_6 - 1);
        String _get_3 = _get_2.get(_minus_6);
        _builder.append(_get_3, "\t\t\t\t\t\t");
        _builder.append("\");");
        _builder.newLineIfNotEmpty();
        _builder.append("\t\t\t\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.append("public static List<String> getOperatorNames(String mutator) {");
        _builder.newLine();
        _builder.append("\t\t\t\t    ");
        _builder.append("List<String> operatorNames =");
        _builder.newLine();
        _builder.append("\t\t\t\t        ");
        _builder.append("new ArrayList<String>();");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.newLine();
        {
          Set<String> _keySet_1 = mutMap.keySet();
          for(final String mut_1 : _keySet_1) {
            _builder.append("\t\t\t\t    ");
            _builder.append("if (mutator.compareTo(\"");
            _builder.append(mut_1, "\t\t\t\t    ");
            _builder.append("\") == 0) {");
            _builder.newLineIfNotEmpty();
            {
              List<String> _get_4 = mutMap.get(mut_1);
              for(final String operator_2 : _get_4) {
                _builder.append("operatorNames.add(\"");
                _builder.append(operator_2);
                _builder.append("\");");
                _builder.newLineIfNotEmpty();
              }
            }
            _builder.append("\t\t\t\t    ");
            _builder.append("}");
            _builder.newLine();
          }
        }
        _builder.append("\t\t\t\t");
        _builder.newLine();
        _builder.append("\t\t\t\t    ");
        _builder.append("return operatorNames;");
        _builder.newLine();
        _builder.append("\t\t\t\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public static MutatorUtils.MutationResults createMutants(");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("String inputFolder,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("String outputFolder,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("String ecoreURI,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("long executionSeed)");
        _builder.newLine();
        _builder.append("\t    ");
        _builder.append("throws ReferenceNonExistingException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("WrongAttributeTypeException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("MaxSmallerThanMinException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("AbstractCreationException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ObjectNoTargetableException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ObjectNotContainedException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("MetaModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("IOException {");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t    ");
        _builder.append("return createMutants(");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("inputFolder,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("outputFolder,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("null,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("true,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("executionSeed);");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public static MutatorUtils.MutationResults createMutants(");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("String inputFolder,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("String outputFolder,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("String[] blockNames,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("boolean registry,");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("long executionSeed)");
        _builder.newLine();
        _builder.append("\t    ");
        _builder.append("throws ReferenceNonExistingException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("WrongAttributeTypeException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("MaxSmallerThanMinException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("AbstractCreationException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ObjectNoTargetableException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ObjectNotContainedException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("MetaModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("ModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t           ");
        _builder.append("IOException {");
        _builder.newLine();
        _builder.append("String ecoreURI =");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("\"");
        String _metaModel = ModelManager.getMetaModel(mutEnvironment.get(0));
        _builder.append(_metaModel, "        ");
        _builder.append("\";");
        _builder.newLineIfNotEmpty();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("List<String> mutatorNames =");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("new ArrayList<String>();");
        _builder.newLine();
        _builder.newLine();
        {
          Set<String> _keySet_2 = mutMap.keySet();
          for(final String mutatorName_1 : _keySet_2) {
            _builder.append("    ");
            _builder.append("mutatorNames.add(");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("    ");
            _builder.append("\"");
            _builder.append(mutatorName_1, "        ");
            _builder.append("\");");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.newLine();
        _builder.append("    ");
        _builder.append("List<List<String>> operatorNames =");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("new ArrayList<List<String>>();");
        _builder.newLine();
        _builder.newLine();
        {
          Set<String> _keySet_3 = mutMap.keySet();
          for(final String mut_2 : _keySet_3) {
            _builder.append("    ");
            _builder.append("List<String> mutatorOperatorNames");
            _builder.append(mut_2, "    ");
            _builder.append(" = getOperatorNames(\"");
            _builder.append(mut_2, "    ");
            _builder.append("\");");
            _builder.newLineIfNotEmpty();
            _builder.newLine();
            _builder.append("    ");
            _builder.append("operatorNames.add(");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("    ");
            _builder.append("mutatorOperatorNames");
            _builder.append(mut_2, "        ");
            _builder.append(");");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.newLine();
        _builder.append("    ");
        _builder.append("String[] arrMutatorNames =");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("new String[mutatorNames.size()];");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("mutatorNames.toArray(");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("arrMutatorNames);");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("String[][] arrOperatorNames =");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("new String[mutatorNames.size()][];");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("int i = 0;");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("for (List<String> mutOpNames :");
        _builder.newLine();
        _builder.append("            ");
        _builder.append("operatorNames) {");
        _builder.newLine();
        _builder.newLine();
        _builder.append("        ");
        _builder.append("String[] arrMutatorOperatorNames =");
        _builder.newLine();
        _builder.append("            ");
        _builder.append("new String[mutOpNames.size()];");
        _builder.newLine();
        _builder.newLine();
        _builder.append("        ");
        _builder.append("mutOpNames.toArray(");
        _builder.newLine();
        _builder.append("            ");
        _builder.append("arrMutatorOperatorNames);");
        _builder.newLine();
        _builder.newLine();
        _builder.append("        ");
        _builder.append("arrOperatorNames[i] =");
        _builder.newLine();
        _builder.append("            ");
        _builder.append("arrMutatorOperatorNames;");
        _builder.newLine();
        _builder.newLine();
        _builder.append("        ");
        _builder.append("i++;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("/*");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* Adapt the caller-supplied input folder to the");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* filesystem location embedded in the Wodel");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* mutation program.");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*/");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("String inputWodelFolder = \"");
        String _replace = project.getLocation().toFile().getAbsolutePath().replace("\\", "/");
        _builder.append(_replace, "    ");
        _builder.append("/data/model\";");
        _builder.newLineIfNotEmpty();
        _builder.newLine();
        _builder.append("Path requestedInput =");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("Paths.get(inputFolder)");
        _builder.newLine();
        _builder.append("         ");
        _builder.append(".toAbsolutePath()");
        _builder.newLine();
        _builder.append("         ");
        _builder.append(".normalize();");
        _builder.newLine();
        _builder.newLine();
        _builder.append("Path internalInput =");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("Paths.get(inputWodelFolder)");
        _builder.newLine();
        _builder.append("         ");
        _builder.append(".toAbsolutePath()");
        _builder.newLine();
        _builder.append("         ");
        _builder.append(".normalize();");
        _builder.newLine();
        _builder.newLine();
        _builder.append("if (!requestedInput.equals(internalInput)) {");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("IOUtils.deleteFolder(");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("internalInput.toString(),");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("\"model\");");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("IOUtils.copyFolder(");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("requestedInput.toFile(),");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("internalInput.toFile(),");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("\"model\");");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("Path inputWodelPath =");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("Paths.get(inputWodelFolder)");
        _builder.newLine();
        _builder.append("             ");
        _builder.append(".toAbsolutePath()");
        _builder.newLine();
        _builder.append("             ");
        _builder.append(".normalize();");
        _builder.newLine();
        _builder.append("    ");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("/*");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* inputWodelFolder = <project>/data/model");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* parent      = <project>/data");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("* parent      = <project>");
        _builder.newLine();
        _builder.append("     ");
        _builder.append("*/");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("Path projectPath =");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("inputWodelPath");
        _builder.newLine();
        _builder.append("            ");
        _builder.append(".getParent()");
        _builder.newLine();
        _builder.append("            ");
        _builder.append(".getParent();");
        _builder.newLine();
        _builder.append("    ");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("Path outputWodelPath =");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("projectPath");
        _builder.newLine();
        _builder.append("            ");
        _builder.append(".resolve(\"data\")");
        _builder.newLine();
        _builder.append("            ");
        _builder.append(".resolve(\"out\")");
        _builder.newLine();
        _builder.append("            ");
        _builder.append(".toAbsolutePath()");
        _builder.newLine();
        _builder.append("            ");
        _builder.append(".normalize();");
        _builder.newLine();
        _builder.append("    ");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("String outputWodelFolder =");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("outputWodelPath.toString();");
        _builder.newLine();
        _builder.append("    ");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("List<String> mutatorList =");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("MutatorUtils.getMutators(");
        _builder.newLine();
        _builder.append("            ");
        _builder.append("projectPath.toFile().listFiles());");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("IOUtils.deleteFolder(");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("outputWodelFolder,");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("\"model\",");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("mutatorList);");
        _builder.newLine();
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("MutatorUtils.MutationResults total =");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("new MutatorUtils.MutationResults();");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("i = 0;");
        _builder.newLine();
        _builder.newLine();
        {
          Set<String> _keySet_4 = mutMap.keySet();
          for(final String mutatorName_2 : _keySet_4) {
            _builder.newLine();
            _builder.append("    ");
            _builder.append("String[] selectedOperators");
            _builder.append(mutatorName_2, "    ");
            _builder.append(" =");
            _builder.newLineIfNotEmpty();
            _builder.append("    ");
            _builder.append("    ");
            _builder.append("blockNames != null");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("        ");
            _builder.append("? blockNames");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("        ");
            _builder.append(": arrOperatorNames[i];");
            _builder.newLine();
            _builder.newLine();
            _builder.append("    ");
            _builder.append("MutatorUtils.MutationResults result");
            _builder.append(mutatorName_2, "    ");
            _builder.append(" =");
            _builder.newLineIfNotEmpty();
            {
              if ((this.standalone == false)) {
                _builder.append("    ");
                _builder.append(mutatorName_2, "    ");
                _builder.append("DynamicAPI.createMutants(");
                _builder.newLineIfNotEmpty();
              } else {
                _builder.append("    ");
                _builder.append(mutatorName_2, "    ");
                _builder.append("StandaloneAPI.createMutants(");
                _builder.newLineIfNotEmpty();
              }
            }
            _builder.append("    ");
            _builder.append("        ");
            _builder.append("selectedOperators");
            _builder.append(mutatorName_2, "            ");
            _builder.append(",");
            _builder.newLineIfNotEmpty();
            _builder.append("    ");
            _builder.append("        ");
            _builder.append("registry,");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("        ");
            _builder.append("executionSeed);");
            _builder.newLine();
            _builder.newLine();
            _builder.append("    ");
            _builder.append("merge(");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("    ");
            _builder.append("total,");
            _builder.newLine();
            _builder.append("    ");
            _builder.append("    ");
            _builder.append("result");
            _builder.append(mutatorName_2, "        ");
            _builder.append(");");
            _builder.newLineIfNotEmpty();
            _builder.newLine();
            _builder.append("    ");
            _builder.append("i++;");
            _builder.newLine();
            _builder.newLine();
          }
        }
        _builder.newLine();
        _builder.newLine();
        _builder.append("Path requestedOutput =");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("Paths.get(outputFolder)");
        _builder.newLine();
        _builder.append("         ");
        _builder.append(".toAbsolutePath()");
        _builder.newLine();
        _builder.append("         ");
        _builder.append(".normalize();");
        _builder.newLine();
        _builder.newLine();
        _builder.append("Path internalOutput =");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("Paths.get(outputWodelFolder)");
        _builder.newLine();
        _builder.append("         ");
        _builder.append(".toAbsolutePath()");
        _builder.newLine();
        _builder.append("         ");
        _builder.append(".normalize();");
        _builder.newLine();
        _builder.newLine();
        _builder.append("if (!requestedOutput.equals(internalOutput)) {");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("Files.createDirectories(");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("requestedOutput);");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("IOUtils.copyFolder(");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("internalOutput.toFile(),");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("requestedOutput.toFile(),");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("\"model\",");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("mutatorList);");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("System.out.println(");
        _builder.newLine();
        _builder.append("        ");
        _builder.append("\"Complete mutant generation process finished.\");");
        _builder.newLine();
        _builder.newLine();
        _builder.append("    ");
        _builder.append("return total;");
        _builder.newLine();
        _builder.append("}\t\t\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("public static void main(String[] args)");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("throws ReferenceNonExistingException,");
        _builder.newLine();
        _builder.append("\t               ");
        _builder.append("WrongAttributeTypeException,");
        _builder.newLine();
        _builder.append("\t               ");
        _builder.append("MaxSmallerThanMinException,");
        _builder.newLine();
        _builder.append("\t               ");
        _builder.append("AbstractCreationException,");
        _builder.newLine();
        _builder.append("\t               ");
        _builder.append("ObjectNoTargetableException,");
        _builder.newLine();
        _builder.append("\t               ");
        _builder.append("ObjectNotContainedException,");
        _builder.newLine();
        _builder.append("\t               ");
        _builder.append("MetaModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t               ");
        _builder.append("ModelNotFoundException,");
        _builder.newLine();
        _builder.append("\t               ");
        _builder.append("IOException {");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t    ");
        _builder.append("if (args.length != 2) {");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("System.err.println(");
        _builder.newLine();
        _builder.append("\t            ");
        _builder.append("\"Use: args[0] = inputFolder; \" +");
        _builder.newLine();
        _builder.append("\t            ");
        _builder.append("\"args[1] = outputFolder\");");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("System.exit(2);");
        _builder.newLine();
        _builder.append("\t    ");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t    ");
        _builder.append("MutatorUtils.MutationResults result =");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("createMutants(args[0], args[1], null, true, System.nanoTime());");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t    ");
        _builder.append("System.out.println(");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("\"WODEL_RESULT mutants=\" +");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("result.getNumMutantsGenerated() +");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("\" mutators=\" +");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("result.getNumMutatorsApplied());");
        _builder.newLine();
        _builder.append("\t");
        _builder.newLine();
        _builder.append("\t    ");
        _builder.append("if (result.getMutatorsApplied() != null) {");
        _builder.newLine();
        _builder.append("\t        ");
        _builder.append("System.out.println(");
        _builder.newLine();
        _builder.append("\t            ");
        _builder.append("\"WODEL_RESULT operators=\" +");
        _builder.newLine();
        _builder.append("\t            ");
        _builder.append("result.getMutatorsApplied());");
        _builder.newLine();
        _builder.append("\t    ");
        _builder.append("}");
        _builder.newLine();
        _builder.append("\t");
        _builder.append("}");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
      }
    }
    return _builder;
  }
}
