/**
 * generated by Xtext
 */
package wodeledu.dsls.validation;

import wodeledu.dsls.validation.AbstractEduTestValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EduTestValidator extends AbstractEduTestValidator {
}
