/*
 * generated by Xtext
 */
package wodeledu.dsls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ModelGraphUiModule extends wodeledu.dsls.ui.AbstractModelGraphUiModule {
	public ModelGraphUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
