/**
 * generated by Xtext
 */
package org.mutatortests.serializer;

import org.mutatortests.serializer.AbstractTestsSyntacticSequencer;

@SuppressWarnings("all")
public class TestsSyntacticSequencer extends AbstractTestsSyntacticSequencer {
}
