/*
 * generated by Xtext
 */
package wodel.dsls;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class WodelUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return wodel.dsls.ui.internal.WodelActivator.getInstance().getInjector("wodel.dsls.Wodel");
	}
	
}
