/**
 * generated by Xtext 2.13.0
 */
package wodeledu.dsls.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import wodeledu.dsls.ModelDrawRuntimeModule;
import wodeledu.dsls.ModelDrawStandaloneSetup;
import wodeledu.dsls.ide.ModelDrawIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ModelDrawIdeSetup extends ModelDrawStandaloneSetup {
  @Override
  public Injector createInjector() {
    ModelDrawRuntimeModule _modelDrawRuntimeModule = new ModelDrawRuntimeModule();
    ModelDrawIdeModule _modelDrawIdeModule = new ModelDrawIdeModule();
    return Guice.createInjector(Modules2.mixin(_modelDrawRuntimeModule, _modelDrawIdeModule));
  }
}
