/**
 * generated by Xtext 2.13.0
 */
package wodel.dsls.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import wodel.dsls.ui.AbstractAspleUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AspleUiModule extends AbstractAspleUiModule {
  public AspleUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
