/*
 * generated by Xtext
 */
package org.mutatorgraph.ui.contentassist

import org.mutatorgraph.ui.contentassist.AbstractMutatorGraphProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MutatorGraphProposalProvider extends AbstractMutatorGraphProposalProvider {
}
