/**
 *
 * $Id$
 */
package mutatorenvironment.validation;

import mutatorenvironment.AttributeInit;
import mutatorenvironment.ObSelectionStrategy;
import mutatorenvironment.ReferenceSet;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EReference;

/**
 * A sample validator interface for {@link mutatorenvironment.CreateObjectMutator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CreateObjectMutatorValidator {
	boolean validate();

	boolean validateType(EClass value);
	boolean validateContainer(ObSelectionStrategy value);
	boolean validateAttributes(EList<AttributeInit> value);
	boolean validateRefType(EReference value);

	boolean validateReferences(EList<ReferenceSet> value);
}
