/**
 *
 * $Id$
 */
package mutatorenvironment.validation;

import mutatorenvironment.IntegerType;


/**
 * A sample validator interface for {@link mutatorenvironment.Mutator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MutatorValidator {
	boolean validate();

	boolean validateMax(Float value);

	boolean validateMin(IntegerType value);

	boolean validateMax(IntegerType value);

	boolean validateMax(int value);

	boolean validateMin(int value);

}
